---
- name: Install and configure NGINX
  hosts: centralRouter
  become: true
  vars:
    nginx_listen_port: 80

  tasks:
    - name: update
      apt:
        update_cache=yes
      tags:
        - update apt

    - name: NGINX | Install NGINX
      apt:
        name: nginx
        state: latest
      notify:
        - restart nginx
      tags:
        - nginx-package

    - name: NGINX | Create NGINX config file from template
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - reload nginx
      tags:
        - nginx-configuration

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes
        
    - name: reload nginx
      systemd:
        name: nginx
        state: reloaded

- name: Network configure
  hosts: all
  become: yes
  tasks:
    - name: Set up NAT and knock on inetRouter
      template: 
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "{{ item.mode }}"
      with_items:
        - { src: "templates/iptables_rules_inet1.ipv4", dest: "/etc/iptables_rules.ipv4", mode: "0644" }
        - { src: "templates/iptables_restore", dest: "/etc/network/if-pre-up.d/iptables", mode: "0755" }
      when: (ansible_hostname == "inetRouter")
    
    - name: Set up knock on inetRouter2
      template: 
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "{{ item.mode }}"
      with_items:
        - { src: "templates/iptables_rules_inet2.ipv4", dest: "/etc/iptables_rules.ipv4", mode: "0644" }
        - { src: "templates/iptables_restore", dest: "/etc/network/if-pre-up.d/iptables", mode: "0755" }
      when: (ansible_hostname == "inetRouter2")

    - name: set up forward packages across routers
      sysctl:
        name: net.ipv4.conf.all.forwarding
        value: '1'
        state: present
      when: "'routers' in group_names"

    - name: Disable the ufw firewall 
      service:
        name: ufw
        state: stopped
        enabled: false
      when: "'routers' in group_names"

    - name: disable default route
      template: 
        src: templates/00-installer-config.yaml
        dest: /etc/netplan/00-installer-config.yaml
        owner: root
        group: root
        mode: 0644
      when: (ansible_hostname != "inetRouter")

    - name: add default gateway for centralRouter
      template: 
        src: "templates/50-vagrant_{{ansible_hostname}}.yaml"
        dest: /etc/netplan/50-vagrant.yaml
        owner: root
        group: root
        mode: 0644

    - name: restart all hosts
      reboot:
        reboot_timeout: 600
